echo ''
echo -e '\e[36m *******************************************************\e[0m'
echo -e '\e[36m*\e[0m		- Elija una opcion -			\e[36m*\e[0m'
echo -e '\e[36m*\e[0m							\e[36m*\e[0m'
echo -e '\e[36m*\e[0m	1-Instalar composer				\e[36m*\e[0m'
echo -e '\e[36m*\e[0m	2-Listar proyectos existentes			\e[36m*\e[0m'
echo -e '\e[36m*\e[0m	3-Crear nuevo proyecto				\e[36m*\e[0m'
echo -e '\e[36m*\e[0m	4-Descargar proyecto de repositorio GitHub	\e[36m*\e[0m'
echo -e '\e[36m*\e[0m	0-Salir						\e[36m*\e[0m'
echo -e '\e[36m*\e[0m							\e[36m*\e[0m'
echo -e '\e[36m *******************************************************\e[0m'
echo ''
echo 'Opcion:'